name: flutter_app1
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  expressions: ^0.2.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.9
  flutter_localizations:
    sdk: flutter
  mate: ^0.0.5
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
